[package]
name = "guest-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
sandboxd-protocol = { path = "../sandboxd-protocol" }
serde.workspace = true
thiserror.workspace = true
zeroize = { version = "1.8.2", features = ["derive"] }
serde_bytes = "0.11.19"
subtle = "2.6.1"

[lints.rust]
unsafe_code = "forbid"

[dev-dependencies]
proptest = "1.9.0"
