#!/usr/bin/env python3
import os
import sys
arguments = [arg for arg in sys.argv[1:] if arg != "--target=x86_64-unknown-linux-musl"]
os.execvp("zig", ["zig", "cc", "-target", "x86_64-linux-musl", *arguments])
